version: "3.9"

services:
  web:
    build: .
#    image: dnd:latest
    container_name: dnd
#    command: python3 app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/src
    ports:
      - "8000:8000"

