# Generated by Django 4.1 on 2023-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('subclass', models.CharField(blank=True, max_length=100)),
                ('base_ability', models.CharField(blank=True, max_length=100)),
                ('img_path', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('full_description', models.JSONField(blank=True)),
                ('advice', models.CharField(blank=True, max_length=1000)),
                ('hit_dice', models.IntegerField(blank=True)),
                ('proficiencies', models.JSONField(blank=True)),
                ('ability', models.JSONField(blank=True)),
                ('class_equipment', models.JSONField(blank=True)),
                ('base_spell_save_dc', models.IntegerField(blank=True)),
                ('spells', models.JSONField(blank=True)),
                ('skills', models.JSONField(blank=True)),
                ('spell_slot', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(blank=True, max_length=100)),
                ('img_path', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('full_description', models.JSONField(blank=True)),
                ('race_bonus', models.JSONField(blank=True)),
                ('max_age', models.IntegerField(blank=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('speed', models.IntegerField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=128)),
                ('else_traits', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
