# Generated by Django 4.1 on 2023-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feats_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('bonus_value', models.IntegerField()),
                ('bonus_skill', models.ManyToManyField(to='character_static_data.skills')),
            ],
            options={
                'ordering': ['feats_name'],
            },
        ),
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(blank=True, max_length=100)),
                ('ability_base', models.ManyToManyField(to='character_static_data.skills')),
            ],
            options={
                'ordering': ['ability_name'],
            },
        ),
    ]
